import struct
from Script.api.struct_helper import *
from Script.project_api.structs import micron_vendor_cmd
class MDWLSV_format_V2(PacketParserComposerABC):
    def __init__(self, payload:bytearray = bytearray(30), start_offset:int = AUTO_OFFSET, end_offset:int = AUTO_OFFSET) -> None:
        super().__init__(payload = payload, start_offset = start_offset, end_offset = end_offset)
        self.MDWLSV_MM_OPEN_BLOCK_EM1_HOST_offset	 = self.add_field(	0	,	0	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_EM1_HOST_SB0_offset	 = self.add_field(	1	,	1	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_TABLE_PTE_offset	 = self.add_field(	2	,	2	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_TABLE_PTE_SB0_offset	 = self.add_field(	3	,	3	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_TEMP_RAIN_offset	 = self.add_field(	4	,	4	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_TEMP_RAIN_SB0_offset	 = self.add_field(	5	,	5	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_NOMAL_HOST_SLC_offset	 = self.add_field(	6	,	6	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_NOMAL_HOST_SLC_SB0_offset	 = self.add_field(	7	,	7	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_WRITE_BOOSTER_offset	 = self.add_field(	8	,	8	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_WRITE_BOOSTER_SB0_offset	 = self.add_field(	9	,	9	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_RPMB_HOST_offset	 = self.add_field(	10	,	10	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_RPMB_HOST_SB0_offset	 = self.add_field(	11	,	11	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_RPMB_GC_offset	 = self.add_field(	12	,	12	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_RPMB_GC_SB0_offset	 = self.add_field(	13	,	13	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_WB_offset	 = self.add_field(	14	,	14	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_WB_SB0_offset	 = self.add_field(	15	,	15	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_EM1_offset	 = self.add_field(	16	,	16	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_EM1_SB0_offset	 = self.add_field(	17	,	17	, 'big')
        self.MDWLSV_SM_OPEN_BLOCK_FTL_SUB_offset	 = self.add_field(	18	,	18	, 'big')
        self.MDWLSV_SM_OPEN_BLOCK_FTL_SUB_SB0_offset	 = self.add_field(	19	,	19	, 'big')
        self.MDWLSV_SM_OPEN_BLOCK_EM1_GC_offset	 = self.add_field(	20	,	20	, 'big')
        self.MDWLSV_SM_OPEN_BLOCK_EM1_GC_SB0_offset	 = self.add_field(	21	,	21	, 'big')
        self.MDWLSV_SM_OPEN_BLOCK_NOMAL_HOST_TLC_offset	 = self.add_field(	22	,	22	, 'big')
        self.MDWLSV_SM_OPEN_BLOCK_NOMAL_HOST_TLC_SB0_offset	 = self.add_field(	23	,	23	, 'big')
        self.MDWLSV_SM_OPEN_BLOCK_NORMAL_GC_offset	 = self.add_field(	24	,	24	, 'big')
        self.MDWLSV_SM_OPEN_BLOCK_NORMAL_GC_SB0_offset	 = self.add_field(	25	,	25	, 'big')
        self.MDWLSV_SM_OPEN_BLOCK_SWAPRAIN_HOST_offset	 = self.add_field(	26	,	26	, 'big')
        self.MDWLSV_SM_OPEN_BLOCK_SWAPRAIN_HOST_SB0_offset	 = self.add_field(	27	,	27	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_TABLE_LOG_offset	 = self.add_field(	28	,	28	, 'big')
        self.MDWLSV_MM_OPEN_BLOCK_TABLE_LOG_SB0_offset	 = self.add_field(	29	,	29	, 'big')
class MDWLSV_format_H(PacketParserComposerABC):
    def __init__(self, payload:bytearray = bytearray(120), start_offset:int = AUTO_OFFSET, end_offset:int = AUTO_OFFSET) -> None:
        super().__init__(payload = payload, start_offset = start_offset, end_offset = end_offset)
        self.mdwlsv_md:list[MDWLSV_format_V2] = []
        for i in range(4):
            self.mdwlsv_md.append(MDWLSV_format_V2(payload, 0+i*30, 30+i*30-1))

class MDWLSV_format(PacketParserComposerABC):
    def __init__(self, payload:bytearray = bytearray(120), start_offset:int = AUTO_OFFSET, end_offset:int = AUTO_OFFSET) -> None:
        super().__init__(payload = payload, start_offset = start_offset, end_offset = end_offset)
        self.Die0_MDWLSV_MM_OPEN_BLOCK_EM1_HOST_offset	 = self.add_field(	0	,	0	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_EM1_HOST_SB0_offset	 = self.add_field(	1	,	1	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_TABLE_PTE_offset	 = self.add_field(	2	,	2	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_TABLE_PTE_SB0_offset	 = self.add_field(	3	,	3	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_TEMP_RAIN_offset	 = self.add_field(	4	,	4	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_TEMP_RAIN_SB0_offset	 = self.add_field(	5	,	5	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_NOMAL_HOST_SLC_offset	 = self.add_field(	6	,	6	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_NOMAL_HOST_SLC_SB0_offset	 = self.add_field(	7	,	7	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_WRITE_BOOSTER_offset	 = self.add_field(	8	,	8	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_WRITE_BOOSTER_SB0_offset	 = self.add_field(	9	,	9	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_RPMB_HOST_offset	 = self.add_field(	10	,	10	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_RPMB_HOST_SB0_offset	 = self.add_field(	11	,	11	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_RPMB_GC_offset	 = self.add_field(	12	,	12	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_RPMB_GC_SB0_offset	 = self.add_field(	13	,	13	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_WB_offset	 = self.add_field(	14	,	14	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_WB_SB0_offset	 = self.add_field(	15	,	15	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_EM1_offset	 = self.add_field(	16	,	16	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_EM1_SB0_offset	 = self.add_field(	17	,	17	, 'big')
        self.Die0_MDWLSV_SM_OPEN_BLOCK_FTL_SUB_offset	 = self.add_field(	18	,	18	, 'big')
        self.Die0_MDWLSV_SM_OPEN_BLOCK_FTL_SUB_SB0_offset	 = self.add_field(	19	,	19	, 'big')
        self.Die0_MDWLSV_SM_OPEN_BLOCK_EM1_GC_offset	 = self.add_field(	20	,	20	, 'big')
        self.Die0_MDWLSV_SM_OPEN_BLOCK_EM1_GC_SB0_offset	 = self.add_field(	21	,	21	, 'big')
        self.Die0_MDWLSV_SM_OPEN_BLOCK_NOMAL_HOST_TLC_offset	 = self.add_field(	22	,	22	, 'big')
        self.Die0_MDWLSV_SM_OPEN_BLOCK_NOMAL_HOST_TLC_SB0_offset	 = self.add_field(	23	,	23	, 'big')
        self.Die0_MDWLSV_SM_OPEN_BLOCK_NORMAL_GC_offset	 = self.add_field(	24	,	24	, 'big')
        self.Die0_MDWLSV_SM_OPEN_BLOCK_NORMAL_GC_SB0_offset	 = self.add_field(	25	,	25	, 'big')
        self.Die0_MDWLSV_SM_OPEN_BLOCK_SWAPRAIN_HOST_offset	 = self.add_field(	26	,	26	, 'big')
        self.Die0_MDWLSV_SM_OPEN_BLOCK_SWAPRAIN_HOST_SB0_offset	 = self.add_field(	27	,	27	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_TABLE_LOG_offset	 = self.add_field(	28	,	28	, 'big')
        self.Die0_MDWLSV_MM_OPEN_BLOCK_TABLE_LOG_SB0_offset	 = self.add_field(	29	,	29	, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_EM1_HOST_offset	 = self.add_field(	0	+ 1 * 30,	0	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_EM1_HOST_SB0_offset	 = self.add_field(	1	+ 1 * 30,	1	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_TABLE_PTE_offset	 = self.add_field(	2	+ 1 * 30,	2	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_TABLE_PTE_SB0_offset	 = self.add_field(	3	+ 1 * 30,	3	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_TEMP_RAIN_offset	 = self.add_field(	4	+ 1 * 30,	4	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_TEMP_RAIN_SB0_offset	 = self.add_field(	5	+ 1 * 30,	5	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_NOMAL_HOST_SLC_offset	 = self.add_field(	6	+ 1 * 30,	6	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_NOMAL_HOST_SLC_SB0_offset	 = self.add_field(	7	+ 1 * 30,	7	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_WRITE_BOOSTER_offset	 = self.add_field(	8	+ 1 * 30,	8	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_WRITE_BOOSTER_SB0_offset	 = self.add_field(	9	+ 1 * 30,	9	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_RPMB_HOST_offset	 = self.add_field(	10	+ 1 * 30,	10	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_RPMB_HOST_SB0_offset	 = self.add_field(	11	+ 1 * 30,	11	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_RPMB_GC_offset	 = self.add_field(	12	+ 1 * 30,	12	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_RPMB_GC_SB0_offset	 = self.add_field(	13	+ 1 * 30,	13	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_WB_offset	 = self.add_field(	14	+ 1 * 30,	14	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_WB_SB0_offset	 = self.add_field(	15	+ 1 * 30,	15	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_EM1_offset	 = self.add_field(	16	+ 1 * 30,	16	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_EM1_SB0_offset	 = self.add_field(	17	+ 1 * 30,	17	+ 1 * 30, 'big')
        self.Die1_MDWLSV_SM_OPEN_BLOCK_FTL_SUB_offset	 = self.add_field(	18	+ 1 * 30,	18	+ 1 * 30, 'big')
        self.Die1_MDWLSV_SM_OPEN_BLOCK_FTL_SUB_SB0_offset	 = self.add_field(	19	+ 1 * 30,	19	+ 1 * 30, 'big')
        self.Die1_MDWLSV_SM_OPEN_BLOCK_EM1_GC_offset	 = self.add_field(	20	+ 1 * 30,	20	+ 1 * 30, 'big')
        self.Die1_MDWLSV_SM_OPEN_BLOCK_EM1_GC_SB0_offset	 = self.add_field(	21	+ 1 * 30,	21	+ 1 * 30, 'big')
        self.Die1_MDWLSV_SM_OPEN_BLOCK_NOMAL_HOST_TLC_offset	 = self.add_field(	22	+ 1 * 30,	22	+ 1 * 30, 'big')
        self.Die1_MDWLSV_SM_OPEN_BLOCK_NOMAL_HOST_TLC_SB0_offset	 = self.add_field(	23	+ 1 * 30,	23	+ 1 * 30, 'big')
        self.Die1_MDWLSV_SM_OPEN_BLOCK_NORMAL_GC_offset	 = self.add_field(	24	+ 1 * 30,	24	+ 1 * 30, 'big')
        self.Die1_MDWLSV_SM_OPEN_BLOCK_NORMAL_GC_SB0_offset	 = self.add_field(	25	+ 1 * 30,	25	+ 1 * 30, 'big')
        self.Die1_MDWLSV_SM_OPEN_BLOCK_SWAPRAIN_HOST_offset	 = self.add_field(	26	+ 1 * 30,	26	+ 1 * 30, 'big')
        self.Die1_MDWLSV_SM_OPEN_BLOCK_SWAPRAIN_HOST_SB0_offset	 = self.add_field(	27	+ 1 * 30,	27	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_TABLE_LOG_offset	 = self.add_field(	28	+ 1 * 30,	28	+ 1 * 30, 'big')
        self.Die1_MDWLSV_MM_OPEN_BLOCK_TABLE_LOG_SB0_offset	 = self.add_field(	29	+ 1 * 30,	29	+ 1 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_EM1_HOST_offset	 = self.add_field(	0	+ 2 * 30,	0	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_EM1_HOST_SB0_offset	 = self.add_field(	1	+ 2 * 30,	1	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_TABLE_PTE_offset	 = self.add_field(	2	+ 2 * 30,	2	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_TABLE_PTE_SB0_offset	 = self.add_field(	3	+ 2 * 30,	3	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_TEMP_RAIN_offset	 = self.add_field(	4	+ 2 * 30,	4	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_TEMP_RAIN_SB0_offset	 = self.add_field(	5	+ 2 * 30,	5	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_NOMAL_HOST_SLC_offset	 = self.add_field(	6	+ 2 * 30,	6	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_NOMAL_HOST_SLC_SB0_offset	 = self.add_field(	7	+ 2 * 30,	7	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_WRITE_BOOSTER_offset	 = self.add_field(	8	+ 2 * 30,	8	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_WRITE_BOOSTER_SB0_offset	 = self.add_field(	9	+ 2 * 30,	9	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_RPMB_HOST_offset	 = self.add_field(	10	+ 2 * 30,	10	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_RPMB_HOST_SB0_offset	 = self.add_field(	11	+ 2 * 30,	11	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_RPMB_GC_offset	 = self.add_field(	12	+ 2 * 30,	12	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_RPMB_GC_SB0_offset	 = self.add_field(	13	+ 2 * 30,	13	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_WB_offset	 = self.add_field(	14	+ 2 * 30,	14	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_WB_SB0_offset	 = self.add_field(	15	+ 2 * 30,	15	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_EM1_offset	 = self.add_field(	16	+ 2 * 30,	16	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_EM1_SB0_offset	 = self.add_field(	17	+ 2 * 30,	17	+ 2 * 30, 'big')
        self.Die2_MDWLSV_SM_OPEN_BLOCK_FTL_SUB_offset	 = self.add_field(	18	+ 2 * 30,	18	+ 2 * 30, 'big')
        self.Die2_MDWLSV_SM_OPEN_BLOCK_FTL_SUB_SB0_offset	 = self.add_field(	19	+ 2 * 30,	19	+ 2 * 30, 'big')
        self.Die2_MDWLSV_SM_OPEN_BLOCK_EM1_GC_offset	 = self.add_field(	20	+ 2 * 30,	20	+ 2 * 30, 'big')
        self.Die2_MDWLSV_SM_OPEN_BLOCK_EM1_GC_SB0_offset	 = self.add_field(	21	+ 2 * 30,	21	+ 2 * 30, 'big')
        self.Die2_MDWLSV_SM_OPEN_BLOCK_NOMAL_HOST_TLC_offset	 = self.add_field(	22	+ 2 * 30,	22	+ 2 * 30, 'big')
        self.Die2_MDWLSV_SM_OPEN_BLOCK_NOMAL_HOST_TLC_SB0_offset	 = self.add_field(	23	+ 2 * 30,	23	+ 2 * 30, 'big')
        self.Die2_MDWLSV_SM_OPEN_BLOCK_NORMAL_GC_offset	 = self.add_field(	24	+ 2 * 30,	24	+ 2 * 30, 'big')
        self.Die2_MDWLSV_SM_OPEN_BLOCK_NORMAL_GC_SB0_offset	 = self.add_field(	25	+ 2 * 30,	25	+ 2 * 30, 'big')
        self.Die2_MDWLSV_SM_OPEN_BLOCK_SWAPRAIN_HOST_offset	 = self.add_field(	26	+ 2 * 30,	26	+ 2 * 30, 'big')
        self.Die2_MDWLSV_SM_OPEN_BLOCK_SWAPRAIN_HOST_SB0_offset	 = self.add_field(	27	+ 2 * 30,	27	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_TABLE_LOG_offset	 = self.add_field(	28	+ 2 * 30,	28	+ 2 * 30, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_TABLE_LOG_SB0_offset	 = self.add_field(	29	+ 2 * 30,	29	+ 2 * 30, 'big')
        self.Die2_MDWLSV_SM_OPEN_BLOCK_SWAPRAIN_HOST_SB0_offset	 = self.add_field(	27	,	27	, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_TABLE_LOG_offset	 = self.add_field(	28	,	28	, 'big')
        self.Die2_MDWLSV_MM_OPEN_BLOCK_TABLE_LOG_SB0_offset	 = self.add_field(	29	,	29	, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_EM1_HOST_offset	 = self.add_field(	0	+ 3 * 30,	0	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_EM1_HOST_SB0_offset	 = self.add_field(	1	+ 3 * 30,	1	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_TABLE_PTE_offset	 = self.add_field(	2	+ 3 * 30,	2	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_TABLE_PTE_SB0_offset	 = self.add_field(	3	+ 3 * 30,	3	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_TEMP_RAIN_offset	 = self.add_field(	4	+ 3 * 30,	4	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_TEMP_RAIN_SB0_offset	 = self.add_field(	5	+ 3 * 30,	5	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_NOMAL_HOST_SLC_offset	 = self.add_field(	6	+ 3 * 30,	6	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_NOMAL_HOST_SLC_SB0_offset	 = self.add_field(	7	+ 3 * 30,	7	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_WRITE_BOOSTER_offset	 = self.add_field(	8	+ 3 * 30,	8	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_WRITE_BOOSTER_SB0_offset	 = self.add_field(	9	+ 3 * 30,	9	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_RPMB_HOST_offset	 = self.add_field(	10	+ 3 * 30,	10	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_RPMB_HOST_SB0_offset	 = self.add_field(	11	+ 3 * 30,	11	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_RPMB_GC_offset	 = self.add_field(	12	+ 3 * 30,	12	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_RPMB_GC_SB0_offset	 = self.add_field(	13	+ 3 * 30,	13	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_WB_offset	 = self.add_field(	14	+ 3 * 30,	14	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_WB_SB0_offset	 = self.add_field(	15	+ 3 * 30,	15	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_EM1_offset	 = self.add_field(	16	+ 3 * 30,	16	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_SWAPRAIN_EM1_SB0_offset	 = self.add_field(	17	+ 3 * 30,	17	+ 3 * 30, 'big')
        self.Die3_MDWLSV_SM_OPEN_BLOCK_FTL_SUB_offset	 = self.add_field(	18	+ 3 * 30,	18	+ 3 * 30, 'big')
        self.Die3_MDWLSV_SM_OPEN_BLOCK_FTL_SUB_SB0_offset	 = self.add_field(	19	+ 3 * 30,	19	+ 3 * 30, 'big')
        self.Die3_MDWLSV_SM_OPEN_BLOCK_EM1_GC_offset	 = self.add_field(	20	+ 3 * 30,	20	+ 3 * 30, 'big')
        self.Die3_MDWLSV_SM_OPEN_BLOCK_EM1_GC_SB0_offset	 = self.add_field(	21	+ 3 * 30,	21	+ 3 * 30, 'big')
        self.Die3_MDWLSV_SM_OPEN_BLOCK_NOMAL_HOST_TLC_offset	 = self.add_field(	22	+ 3 * 30,	22	+ 3 * 30, 'big')
        self.Die3_MDWLSV_SM_OPEN_BLOCK_NOMAL_HOST_TLC_SB0_offset	 = self.add_field(	23	+ 3 * 30,	23	+ 3 * 30, 'big')
        self.Die3_MDWLSV_SM_OPEN_BLOCK_NORMAL_GC_offset	 = self.add_field(	24	+ 3 * 30,	24	+ 3 * 30, 'big')
        self.Die3_MDWLSV_SM_OPEN_BLOCK_NORMAL_GC_SB0_offset	 = self.add_field(	25	+ 3 * 30,	25	+ 3 * 30, 'big')
        self.Die3_MDWLSV_SM_OPEN_BLOCK_SWAPRAIN_HOST_offset	 = self.add_field(	26	+ 3 * 30,	26	+ 3 * 30, 'big')
        self.Die3_MDWLSV_SM_OPEN_BLOCK_SWAPRAIN_HOST_SB0_offset	 = self.add_field(	27	+ 3 * 30,	27	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_TABLE_LOG_offset	 = self.add_field(	28	+ 3 * 30,	28	+ 3 * 30, 'big')
        self.Die3_MDWLSV_MM_OPEN_BLOCK_TABLE_LOG_SB0_offset	 = self.add_field(	29	+ 3 * 30,	29	+ 3 * 30, 'big')





