from enum import Enum, IntEnum
from Script.api.ufs_api.defines.bit_define import BIT
from Script.api.ufs_api.defines.bit_define import BIT0, BIT1, BIT2, BIT3, BIT7

class VB_GROUP(IntEnum):
    HIDDEN_BLK_USE = 0
    LIST_BLK = 1
    LIST_INDEX_BLK = 2
    TMP_CODE_BLK = 3
    CURRENT_PTE = 4
    LOG_TAB_BLK = 5
    CURRENT_L2_SLC = 6
    CURRENT_L2_MLC = 7
    FREEZE_L2_BLK = 8
    CURRENT_DATA_GC_BLK_SLC = 9
    CURRENT_DATA_GC_BLK_MLC = 10
    INCOMPLETE_BLK_SLC = 11
    INCOMPLETE_BLK_MLC = 12
    CURRENT_L1 = 13
    PTE_POOL = 14
    STATIC_SLC_USED_BLK = 15
    USED_BLK_POOL_SLC = 16
    USED_BLK_POOL_MLC = 17
    CURRENT_L3_SLC = 18
    CURRENT_L3_MLC = 19
    REFRESH_LINE = 20
    RAIN_SWAP_NO_OBR_SLC_L2_SLC =21
    RAIN_SWAP_NO_OBR_TLC_L2_SLC =22
    RAIN_SWAP_NO_OBR_TLC_L2_TLC =23
    RAIN_SWAP_NO_OBR_BLK = 24
    RAIN_SWAP_TLC_CURSOR_BLK = 25
    FREE_BLK_QUEUE_SLC = 26
    FREE_BLK_QUEUE_MLC = 27
    FREE_BLK_QUEUE_TABLE = 28
    TMP_ERASE_BLK_SLC = 29
    TMP_ERASE_BLK_MLC = 30
    TMP_ERASE_BLK_TABLE = 31
    TMP_USED_BLK_SLC = 32
    TMP_USED_BLK_MLC = 33
    TMP_USED_BLK_TABLE = 34
    TMP_REMOVE_BLK_SLC = 35
    TMP_REMOVE_BLK_MLC = 36
    TMP_REMOVE_BLK_TABLE = 37
    REFERENCE_QUEUE_SLC = 38
    REFERENCE_QUEUE_MLC = 39
    REVOKE_BLK = 40
    REMAP_DATA_GC_BLK_SLC = 41
    REMAP_DATA_GC_BLK_MLC = 42
    RPMB_COLLECT_BLK = 43
    PRE_ERASE_BLK = 44
    TMP_PRE_ERASE = 45
    PURGE_WAIT_ERASE_SLC = 46
    PURGE_WAIT_ERASE_MLC = 47
    DRVLOG_BLK = 48
    CONSTRAINT_QUEUE = 49
    TMP_FORCE_PTE_GC_TARGET = 50
    RESERVED_VB_GROUP0 = 51
    RESERVED_VB_GROUP1 = 52
    RESERVED_VB_GROUP2 = 53
    RESERVED_VB_GROUP3 = 54
    SELF_PE_ERASE_BLK = 55
    CONFIG_NUM_LIST_GROUP = 56
    