import struct
from Script.api.struct_helper import *

class GetFwConfiguration(PacketParserComposerABC):
    def __init__(self, payload:bytearray = bytearray(128), start_offset:int = AUTO_OFFSET, end_offset:int = AUTO_OFFSET) -> None:
        super().__init__(payload = payload, start_offset = start_offset, end_offset = end_offset)
        self.TotalFieldCounts = self.add_field(0, 3, 'little')
        self.NumberOfTotalDie = self.add_field(4, 7, 'little')
        self.NumberOfChannels = self.add_field(8, 11, 'little')
        self.NumberOfBlocksPerPlane = self.add_field(12, 15, 'little')
        self.NumberOfPhysicalBlocks = self.add_field(16, 19, 'little')
        self.NumberOfPagesPerTlcBlock = self.add_field(20, 23, 'little')
        self.NumberOfPagesPerSlcBlock = self.add_field(24, 27, 'little')
        self.SizeOfPhysicalPage = self.add_field(28, 31, 'little')
        self.SizeOfPhysicalAddressUnit = self.add_field(32, 35, 'little')
        self.NumberOfBlocksInSuperlock= self.add_field(36, 39, 'little')
        self.CountOfAllSuperlocks = self.add_field(40, 43, 'little')
        self.VPCountPerPhysicalPage = self.add_field(44, 47, 'little')
        self.MetadataSpareSizePerKB = self.add_field(48, 51, 'little')
        self.ECCSpareSizePerKB = self.add_field(52, 55, 'little')
        self.DMMaximumReplacedBlockCountForBBRemapPerPlane = self.add_field(56, 59, 'little')
        self.FirstLogicalVBNumberForHostData = self.add_field(60, 63, 'little')
        self.PVTLCVBChunkSize = self.add_field(64, 67, 'little')
        self.PVSLCVBSubChunkCount = self.add_field(68, 71, 'little')
        self.PVTLCVBSubChunkCount = self.add_field(72, 75, 'little')
        self.TheFirstLogVBOfStaticPool = self.add_field(76, 79, 'little')
        self.TheFirstLogVBOfDynamicPool = self.add_field(80, 83, 'little')
        self.TheFirstLogVBOfTableVB = self.add_field(84, 87, 'little')
        self.MaxLateReplVBCountStaticPool = self.add_field(88, 91, 'little')
        self.MaxLateReplVBCountDynamicPool = self.add_field(92, 95, 'little')
        self.MaxEarlyBBCountPerPlane = self.add_field(96, 99, 'little')
        self.MaxLateReplVBCountNoGBBStaticPool = self.add_field(100, 103, 'little')
        self.MaxLateReplVBCountNoGBBtDynamicPool = self.add_field(104, 107, 'little')
        self.MaxGBBCount = self.add_field(108, 111, 'little')
        self.MaxRecoverBBCount = self.add_field(112, 115, 'little')
        self.littleUnmapClearBitRegionThreshold = self.add_field(116, 119, 'little')
        self.SLCPVTSizeInByte = self.add_field(120, 123, 'little')        
        self.TLCPVTSizeInByte = self.add_field(124, 127, 'little')
        #self.Reserved = self.add_field(128, 4095, 'little')
