import struct
from Script.api.struct_helper import *
from Script.project_api.structs import micron_vendor_cmd

class VU_40C2_struct(PacketParserComposerABC):
    def __init__(self, payload: bytearray = bytearray(176), start_offset:int = AUTO_OFFSET, end_offset:int = AUTO_OFFSET) -> None:
        super().__init__(payload = payload, start_offset = start_offset, end_offset = end_offset)
        self.GC_trigger_fields = self.add_field(0, 3, 'little')
        self.GC_trigger_type = self.add_field(4, 7, 'little') 
        self.start_bg_gc_vb_cnt_normal = self.add_field(8, 11, 'little') 
        self.stop_bg_gc_vb_cnt_normal = self.add_field(12, 15, 'little') 
        self.start_fg_gc_vb_cnt_normal = self.add_field(16, 19, 'little') 
        self.l20_not_applicable = self.add_field(20,23,'little')
        self.wb_slc_cache_vb_size_ls0 = self.add_field(24,27,'little')
        self.wb_slc_cache_vb_size_ls100 = self.add_field(28,31,'little') 
        self.max_size_to_reduce_wb_size = self.add_field(32, 35,'little') 
        self.wb_available_size = self.add_field(36,39,'little') 
        self.invalid_vb_cnt_normal = self.add_field(40,43,'little') 
        self.used_slc_vb_cnt = self.add_field(44,47,'little')
        self.used_tlc_vb_cnt = self.add_field(48,51,'little')
        self.used_vb_cnt_in_slc_stale_zone_list = self.add_field(52,55,'little')
        self.vb_cnt_in_LOCKED_SRC_and_cnt_of_open_vb_normal = self.add_field(56,59,'little')
        self.wb_slc_cache_stale_zone_size_ls0 = self.add_field(60,63,'little')
        self.wb_slc_cache_stale_zone_size_ls100 = self.add_field(64,67,'little')
        self.flag_show_IGC_trigger_in_normal = self.add_field(68,71, 'little')
        self.VPs_be_written_to_trigger_IGC_in_normal = self.add_field(72,75,'little')
        self.vb_cnt_in_LOCKED_SRC_list_for_normal = self.add_field(76,79,'little')
        self.start_filling_GC_target_with_dummy_in_normal = self.add_field(80,83,'little')
        self.l84_not_applicable = self.add_field(84,87,'little')
        self.start_bg_gc_vb_cnt_em1 = self.add_field(88,91,'little')
        self.stop_bg_gc_vb_cnt_em1 = self.add_field(92,95,'little')
        self.start_fg_gc_vb_cnt_em1 = self.add_field(96,99,'little')
        self.l100_not_applicable = self.add_field(100,103,'little')
        self.invalid_vb_cnt_em1 = self.add_field(104,107,'little')
        self.vb_cnt_in_LOCKED_SRC_and_cnt_of_open_vb_em1 = self.add_field(108,111,'little')
        self.flag_show_IGC_trigger_in_em1 = self.add_field(112,115,'little')
        self.VPs_be_written_to_trigger_IGC_in_em1 = self.add_field(116,119,'little')
        self.vb_cnt_in_LOCKED_SRC_list_for_em1 = self.add_field(120,123,'little')
        self.start_filling_GC_target_with_dummy_in_em1 = self.add_field(124,127,'little')
        self.num_of_vb_allc_for_using_em1 = self.add_field(128,131,'little')
        self.noraml_area_IGC_stop_threshold = self.add_field(132,135,'little')
        self.em1_area_IGC_stop_threshold = self.add_field(136,139,'little')
        self.normal_area_total_vb_cnt = self.add_field(140,143,'little')
        self.normal_area_remained_vb_cnt = self.add_field(144,147,'little')
        self.l148_not_applicable = self.add_field(148,151,'little')
        self.l152_not_applicable = self.add_field(152,155,'little')
        self.get_last_bkop_status = self.add_field(156,159,'little')
        self.num_of_invalid_entries_in_normal = self.add_field(160,163,'little')
        self.num_of_fragmented_vb_in_normal = self.add_field(164,167,'little')
        self.num_of_invalid_entries_in_em1 = self.add_field(168,171,'little')
        self.num_of_fragmented_vb_in_em1 = self.add_field(172,175,'little')
        

